version: 0.0.1
description: a template for go cli tools
parameters:
- name: RepoName
  prompt: "Repository name"
  required: true
- name: OrgName
  prompt: "Organization or user name"
  required: true